{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

    {if ne( $attribute_base, 'ContentObjectAttribute' )}
        {def $id_base = concat( 'ezcoa-', $attribute_base, '-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
    {else}
        {def $id_base = concat( 'ezcoa-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
    {/if}


    <div class="form-inline date">
        <label class="sr-only" for="{$id_base}_hour">{'Hour'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_hour"
               class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
               placeholder="{'Hour'|i18n( 'design/standard/content/datatype' )}"
               type="text" name="{$attribute_base}_time_hour_{$attribute.id}" size="3"
               value="{if $attribute.content.is_valid}{$attribute.content.hour}{/if}"/>

        <label class="sr-only" for="{$id_base}_minute">{'Minute'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_minute"
               class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
               placeholder="{'Minute'|i18n( 'design/standard/content/datatype' )}"
               type="text" name="{$attribute_base}_time_minute_{$attribute.id}" size="3"
               value="{if $attribute.content.is_valid}{$attribute.content.minute}{/if}"/>

        {if $attribute.contentclass_attribute.data_int2|eq(1)}
            <label class="sr-only" for="{$id_base}_second">{'Second'|i18n( 'design/standard/content/datatype' )}:</label>
            <input id="{$id_base}_second"
                   class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                   placeholder="{'Second'|i18n( 'design/standard/content/datatype' )}"
                   type="text" name="{$attribute_base}_time_second_{$attribute.id}" size="3"
                   value="{if $attribute.content.is_valid}{$attribute.content.second}{/if}"/>
        {/if}

    </div>
{/default}